#!/bin/bash
if [ -z "$1" ]
  then
    echo "Git repo url in the SSH form must be supplied"
    echo "Error: No argument supplied"
    exit 1
fi
proto=$(echo "$1" | cut -d'@' -f 1)
if [ $proto != "git" ]; then
    echo "Git repo url in the SSH form must be supplied"
    echo "Error: not a valid SSH url"
    exit 1
fi

dirname=$(echo "$1" | cut -d'/' -f 2 | cut -d'.' -f 1)
#echo $dirname
git rm -f --cached $dirname > /dev/null
git submodule add $1 $dirname
exit 0
